const fs = require('fs');
const path = require('path');
const postcss = require('postcss');
const tailwindcss = require('tailwindcss');
const autoprefixer = require('autoprefixer');

const root = path.resolve(__dirname, '..');
const stylesDir = path.join(root, 'src/styles/components');
const generatedDir = path.join(root, 'src/generated');
const generatedTs = path.join(generatedDir, 'stylesContent.ts');
const outCss = path.join(root, 'dist/react-core-ts.css');

const componentFiles = [
  'modern-input.css',
  'qbs-fallbacks.css',
  'autocomplete.css',
  'treedropdown.css',
  'selectedautocomplete.css',
  'tooltip.css',
];

async function buildStyles() {
  const componentCss = componentFiles
    .map((file) => fs.readFileSync(path.join(stylesDir, file), 'utf8'))
    .join('\n\n');

  // Generate only the Tailwind utilities/components used by this library.
  const tailwindInput = '@tailwind components;\n@tailwind utilities;\n';
  const tailwindResult = await postcss([
    tailwindcss,
    autoprefixer,
  ]).process(tailwindInput, {
    from: path.join(root, 'src/styles/library-entry.css'),
  });

  const css = `${tailwindResult.css}\n\n${componentCss}\n`;

  fs.mkdirSync(path.dirname(outCss), { recursive: true });
  fs.mkdirSync(generatedDir, { recursive: true });

  fs.writeFileSync(outCss, css);
  fs.writeFileSync(
    generatedTs,
    `/** Auto-generated by scripts/build-styles.js — do not edit */\n` +
      `export const STYLES = ${JSON.stringify(css)};\n`
  );

  console.log(
    `Built styles → dist/react-core-ts.css (${Math.round(css.length / 1024)} KB)`
  );
}

buildStyles().catch((err) => {
  console.error(err);
  process.exit(1);
});
